pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            steps {
                stage('checkout') {
                    steps {
                        checkout scm
                    }
                }
                stage('instalar dependencias') {
                    steps {
                        sh 'npm install'
                    }
                }
                stage('ejecutar tests') {
                    steps {
                        sh 'npm run test'
                    }
                }
                stage('realizar build') {
                    steps {
                        sh 'npm run build'
                    }
                }
            }
        }
    }
}
